- name: Installation de Apache2 sur Ubuntu
  apt:
    name: apache2
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Demarrage du service apache2
  service:
    name: apache2
    state: started
  when: ansible_facts['os_family'] == "Debian"
  
- name: Copie du fichier index.html
  copy:
    src: "/playbooks/templates/index.html
    dest: "var/www/html/index.html"  
  when: ansible_facts['os_family'] == "Debian"