- hosts: webserver
  remote_user: root
  vars_files:
    - ../vars/secret.yml
  tasks:
    - name : "Creation utilisateurs"
      user:
        name: "{{ item.name }}"
        password: "{{ item.pswd | password_hash('sha512') }}"
      loop:
        - name: nicolas
          pswd: "{{ secret_password_nicolas }}"
        - name: supdevinci
          pswd: "{{ secret_password_supdevinci }}"
